// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNuU6uXOEhLtt53GS2w-yB7JftozSeM4',
    appId: '1:35074304858:android:d05872e261cf304e7b6163',
    messagingSenderId: '35074304858',
    projectId: 'todo-f3741',
    storageBucket: 'todo-f3741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kq7dv1vohYnbirVrJo9Va8_Y_qoD1_E',
    appId: '1:35074304858:ios:05509b83cfc1c1997b6163',
    messagingSenderId: '35074304858',
    projectId: 'todo-f3741',
    storageBucket: 'todo-f3741.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kq7dv1vohYnbirVrJo9Va8_Y_qoD1_E',
    appId: '1:35074304858:ios:a158bdaa133078767b6163',
    messagingSenderId: '35074304858',
    projectId: 'todo-f3741',
    storageBucket: 'todo-f3741.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
